version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
    container_name: python-app
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python3 redis_test.py

volumes:
  redis_data:
